"""dropped the user_profile on trnasactions

Revision ID: 009ffcb86aad
Revises: 269e8f3caa2c
Create Date: 2023-10-27 15:40:11.601183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009ffcb86aad'
down_revision = '269e8f3caa2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_user_profile_users_profile', type_='foreignkey')
        batch_op.drop_column('user_profile')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_profile', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_transactions_user_profile_users_profile', 'users_profile', ['user_profile'], ['id'])

    # ### end Alembic commands ###
