"""created the relationship between users and users_profile models

Revision ID: 0563d639c26b
Revises: 5cc5bfebf582
Create Date: 2023-10-27 02:27:21.775227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0563d639c26b'
down_revision = '5cc5bfebf582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_profile_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_profile_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
