"""relationship between walled and user_prof

Revision ID: 0693c9eb0477
Revises: 2ea8895dd7f3
Create Date: 2023-10-27 20:18:03.014423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0693c9eb0477'
down_revision = '2ea8895dd7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_prof_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_wallets_user_prof_id_users_profile'), 'users_profile', ['user_prof_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_wallets_user_prof_id_users_profile'), type_='foreignkey')
        batch_op.drop_column('user_prof_id')

    # ### end Alembic commands ###
