"""created  the beneficiary tables

Revision ID: 095cbac5583e
Revises: c264e15de0ff
Create Date: 2023-11-01 12:54:49.604664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095cbac5583e'
down_revision = 'c264e15de0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('Account', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###
