"""added  the  association table btweeen beneficiary and user_profile

Revision ID: 118f24ab9896
Revises: e33460206cf2
Create Date: 2023-10-27 17:18:59.876923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118f24ab9896'
down_revision = 'e33460206cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=True),
    sa.Column('beneficiary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], name=op.f('fk_user_beneficiaries_beneficiary_id_beneficiaries')),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users_profile.id'], name=op.f('fk_user_beneficiaries_user_profile_id_users_profile')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_beneficiaries')
    # ### end Alembic commands ###
