"""added association table 

Revision ID: 1399d2ed3461
Revises: 70645c90fe8f
Create Date: 2023-10-27 17:57:42.442564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1399d2ed3461'
down_revision = '70645c90fe8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
