"""added  transaction_fee to the transactinos 

Revision ID: 226cda17e5a7
Revises: c98f5baf8794
Create Date: 2023-11-02 11:34:54.299464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226cda17e5a7'
down_revision = 'c98f5baf8794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_fee', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('transaction_fee')

    # ### end Alembic commands ###
