"""set up the relationships for sending money 

Revision ID: 269e8f3caa2c
Revises: aa7b4d340fe0
Create Date: 2023-10-27 14:43:11.169261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269e8f3caa2c'
down_revision = 'aa7b4d340fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('power_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['users_profile.id'], name=op.f('fk_user_beneficiaries_hero_id_users_profile')),
    sa.ForeignKeyConstraint(['power_id'], ['beneficiaries.id'], name=op.f('fk_user_beneficiaries_power_id_beneficiaries')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_profile', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_user_profile_users_profile'), 'users_profile', ['user_profile'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_user_profile_users_profile'), type_='foreignkey')
        batch_op.drop_column('user_profile')

    op.drop_table('user_beneficiaries')
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###
