"""added user_profile_id relationship on Beneficiary

Revision ID: 289e2c629581
Revises: 44e6da1e2c4c
Create Date: 2023-10-27 16:02:28.369733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289e2c629581'
down_revision = '44e6da1e2c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_beneficiaries_user_profile_id_users_profile'), 'users_profile', ['user_profile_id'], ['id'])

    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('beneficiary_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_user_beneficiaries_hero_id_users_profile', type_='foreignkey')
        batch_op.drop_constraint('fk_user_beneficiaries_power_id_beneficiaries', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_beneficiaries_user_profile_id_users_profile'), 'users_profile', ['user_profile_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_beneficiaries_beneficiary_id_beneficiaries'), 'beneficiaries', ['beneficiary_id'], ['id'])
        batch_op.drop_column('power_id')
        batch_op.drop_column('hero_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('power_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_beneficiaries_beneficiary_id_beneficiaries'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_beneficiaries_user_profile_id_users_profile'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_beneficiaries_power_id_beneficiaries', 'beneficiaries', ['power_id'], ['id'])
        batch_op.create_foreign_key('fk_user_beneficiaries_hero_id_users_profile', 'users_profile', ['hero_id'], ['id'])
        batch_op.drop_column('beneficiary_id')
        batch_op.drop_column('user_profile_id')

    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_beneficiaries_user_profile_id_users_profile'), type_='foreignkey')
        batch_op.drop_column('user_profile_id')

    # ### end Alembic commands ###
