"""added satatus column on the userprofile table

Revision ID: 2e7a3b4dc2bd
Revises: c12a9a52852b
Create Date: 2023-11-03 20:11:32.431032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7a3b4dc2bd'
down_revision = 'c12a9a52852b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_profile', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
