"""changed the name to sender_id

Revision ID: 2ea8895dd7f3
Revises: d88473b2d746
Create Date: 2023-10-27 18:48:28.016811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea8895dd7f3'
down_revision = 'd88473b2d746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_beneficiaries_sender_id_users_profile'), 'users_profile', ['sender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_beneficiaries_sender_id_users_profile'), type_='foreignkey')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
