"""dropped wallet relationship 

Revision ID: 2f0f68516fa3
Revises: dbaf7d388793
Create Date: 2023-10-27 03:00:36.853570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0f68516fa3'
down_revision = 'dbaf7d388793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wallets_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_wallets_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
