"""changed the name to sender_id

Revision ID: 2f5d57bcccc3
Revises: b72857abc706
Create Date: 2023-10-27 18:47:36.998680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5d57bcccc3'
down_revision = 'b72857abc706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_beneficiaries_user_profile_id_users_profile'), 'users_profile', ['user_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_beneficiaries_user_profile_id_users_profile'), type_='foreignkey')
        batch_op.drop_column('user_profile_id')

    # ### end Alembic commands ###
