"""created  the many to many relationship between userprof and beneficiaries

Revision ID: 40ed8648b2f2
Revises: 70f74e0ec41f
Create Date: 2023-11-01 13:20:54.243900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ed8648b2f2'
down_revision = '70f74e0ec41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('beneficiary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_beneficiaries_sender_id_users_profile'), 'users_profile', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_beneficiaries_beneficiary_id_beneficiaries'), 'beneficiaries', ['beneficiary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_beneficiaries_beneficiary_id_beneficiaries'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_beneficiaries_sender_id_users_profile'), type_='foreignkey')
        batch_op.drop_column('beneficiary_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
