"""added association table 

Revision ID: 419712c8f71e
Revises: 1399d2ed3461
Create Date: 2023-10-27 18:25:40.654687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419712c8f71e'
down_revision = '1399d2ed3461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_beneficiaries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_beneficiaries',
    sa.Column('user_profile_id', sa.INTEGER(), nullable=True),
    sa.Column('beneficiary_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], name='fk_user_beneficiaries_beneficiary_id_beneficiaries'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users_profile.id'], name='fk_user_beneficiaries_user_profile_id_users_profile')
    )
    # ### end Alembic commands ###
