"""added the sender_id relationship  on trnasactions

Revision ID: 44e6da1e2c4c
Revises: 009ffcb86aad
Create Date: 2023-10-27 15:41:03.238525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e6da1e2c4c'
down_revision = '009ffcb86aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_sender_id_users_profile'), 'users_profile', ['sender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_sender_id_users_profile'), type_='foreignkey')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
