"""added account to the user_profile 

Revision ID: 5c9c0960073d
Revises: eb69f138c553
Create Date: 2023-10-27 13:22:41.313256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9c0960073d'
down_revision = 'eb69f138c553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Account', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_profile', schema=None) as batch_op:
        batch_op.drop_column('Account')

    # ### end Alembic commands ###
