"""added a gender column to user profiles

Revision ID: 6308f9b43a6b
Revises: 2e7a3b4dc2bd
Create Date: 2023-11-07 21:35:15.952782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6308f9b43a6b'
down_revision = '2e7a3b4dc2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_profile', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
