"""replaced roles with is_admin column

Revision ID: b2958c02452d
Revises: 2e072c3d3a27
Create Date: 2023-10-27 01:43:51.467759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2958c02452d'
down_revision = '2e072c3d3a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Integer(), nullable=True))
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('roles')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
