"""chaning the name to user_profile_id

Revision ID: b72857abc706
Revises: 1ba6fad6fdfe
Create Date: 2023-10-27 18:45:01.634487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72857abc706'
down_revision = '1ba6fad6fdfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_beneficiaries_user_profile_id_users_profile', type_='foreignkey')
        batch_op.drop_column('user_profile_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_profile_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_beneficiaries_user_profile_id_users_profile', 'users_profile', ['user_profile_id'], ['id'])

    # ### end Alembic commands ###
