"""relationship established between walletActivity, Transaction and user_profile tables

Revision ID: bef15edefe3e
Revises: c55d79af26e8
Create Date: 2023-10-30 14:54:32.028464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef15edefe3e'
down_revision = 'c55d79af26e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_wallet_activities_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_wallet_activities_transaction_id_transactions'), 'transactions', ['transaction_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_wallet_activities_user_id_users_profile'), 'users_profile', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_wallet_activities_user_id_users_profile'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_wallet_activities_transaction_id_transactions'), type_='foreignkey')
        batch_op.create_foreign_key('fk_wallet_activities_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
