"""added uniquw transaction_id to the transactinos 

Revision ID: c98f5baf8794
Revises: 7b4f0a960edd
Create Date: 2023-11-02 10:55:44.841021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98f5baf8794'
down_revision = '7b4f0a960edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
