"""added receiver and senser name to trasnsactions table

Revision ID: d21d1df42c75
Revises: 226cda17e5a7
Create Date: 2023-11-02 12:20:16.033053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21d1df42c75'
down_revision = '226cda17e5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receiver_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('receiver_name')
        batch_op.drop_column('sender_name')

    # ### end Alembic commands ###
