"""deropped the balance col in wallet

Revision ID: ded3156f40a6
Revises: 40ed8648b2f2
Create Date: 2023-11-01 20:04:08.490558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded3156f40a6'
down_revision = '40ed8648b2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
