"""removed  the uneccessary association table btweeen beneficiary and user_profile

Revision ID: e33460206cf2
Revises: 289e2c629581
Create Date: 2023-10-27 16:43:36.907016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33460206cf2'
down_revision = '289e2c629581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_beneficiaries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_beneficiaries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_profile_id', sa.INTEGER(), nullable=True),
    sa.Column('beneficiary_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], name='fk_user_beneficiaries_beneficiary_id_beneficiaries'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users_profile.id'], name='fk_user_beneficiaries_user_profile_id_users_profile'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
